name: Code Quality

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        
    - name: Install linting tools
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort mypy pylint
        
    - name: Run Black (formatting check)
      run: |
        black --check --diff .
        
    - name: Run isort (import sorting check)
      run: |
        isort --check-only --diff .
        
    - name: Run flake8
      run: |
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Run mypy (type checking)
      run: |
        mypy . --ignore-missing-imports || true
        
    - name: Run pylint
      run: |
        pylint **/*.py --exit-zero --reports=y > pylint-report.txt
        
    - name: Upload pylint report
      uses: actions/upload-artifact@v4
      with:
        name: pylint-report
        path: pylint-report.txt

  complexity:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install tools
      run: |
        pip install radon
        
    - name: Calculate cyclomatic complexity
      run: |
        radon cc . -a -nb
        
    - name: Calculate maintainability index
      run: |
        radon mi . -nb
